### ISSUE TITLE
Uglify crashes with bad JS

### ISSUE THREAD

**Issue by johndhancock** [DallasMorningNews/generator-dmninteractives#15]
Looks like errors in customJS.js are crashing gulp when it tries to uglify it. 

`Starting 'js'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/interactives/working/oil-kings/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/interactives/working/oil-kings/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/interactives/working/oil-kings/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2026:9)
    at token_error (eval at <anonymous> (/interactives/working/oil-kings/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2034:9)
    at unexpected (eval at <anonymous> (/interactives/working/oil-kings/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2040:9)
    at semicolon (eval at <anonymous> (/interactives/working/oil-kings/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2060:56)
    at simple_statement (eval at <anonymous> (/interactives/working/oil-kings/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2240:73)
    at eval (eval at <anonymous> (/interactives/working/oil-kings/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2113:19)
    at eval (eval at <anonymous> (/interactives/working/oil-kings/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2073:24)
    at block_ (eval at <anonymous> (/interactives/working/oil-kings/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2353:20)
tc02fd0h8dhjfd:oil-kings jhancock$ gulp`

**Comment by hobbes7878** [comment]
I can't stop the process kill, but if I can give you a nicely formatted error message like so:

![image](https://cloud.githubusercontent.com/assets/2772078/14474871/af1e8bd6-00c4-11e6-858c-d4c7ed498cae.png)

can you dig?

**Comment by hobbes7878** [comment]
OK, I'm adding [jshint](http://jshint.com/) to all js processing tasks. That should give you a helpful idea what's fucked. Will push with next point release after I figure out what we're going to do with the image cache.
